*** Variables ***
&{Login}

...    input_Usuario=id:field-1
...    input_Senha=id:field-2
...    button_Acessar=xpath://*[@id="__next"]/div[2]/div[1]/div/div[1]/form/button
...    link_SaibaMais=xpath://*[@id="__next"]/div[2]/div[1]/div/div[1]/div[2]/p[2]/a
...    link_FaleComercial=xpath://*[@id="__next"]/div[2]/div[1]/div/div[2]/a/span
...    button_Logoff=xpath://*[@id="__next"]/div/div[1]/div/div[2]/div[3]/button
...    button_LoginAmbienteProd=xpath://*[@id="__next"]/div[1]/button
